apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    io.kompose.service: audit-web-eventhub
  name: audit-web-eventhub
spec:
  ports:
    - name: "8080"
      port: 8080
  type: LoadBalancer
  selector:
    io.kompose.service: audit-web-eventhub
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: audit-web-eventhub
  name: audit-web-eventhub
spec:
  replicas: 1
  minReadySeconds: 30
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      io.kompose.service: audit-web-eventhub
  template:
    metadata:
      labels:
        io.kompose.service: audit-web-eventhub
    spec:
      containers:
        - name: audit-web-eventhub
          image: fintlabs.azurecr.io/audit-web-eventhub:PR-3.3
          ports:
            - containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 5
            timeoutSeconds: 5
            httpGet:
              port: 8080
              path: /actuator/health
          resources:
            limits:
              memory: "12Gi"
              cpu: "4"
            requests:
              cpu: "100m"
              memory: "256Mi"
          envFrom:
            - configMapRef:
                name: fint-environment
            - secretRef:
                name: fint-audit-web-eventhub
          env:
            - {name: JAVA_TOOL_OPTIONS, value: '-XX:+ExitOnOutOfMemoryError -Xmx10G -verbose:gc'}
            - {name: AZURE_LOG_LEVEL, value: info}
            - {name: logging.level.no.fint.audit.web.repository.InMemoryCheckpointStore, value: warn}
            - {name: logging.level.com.azure.messaging.eventhubs.PartitionBasedLoadBalancer, value: warn}
